name: Daily News Briefing

on:
  schedule:
    - cron: '0 9 * * *' # Runs every day at 09:00 UTC (9 AM UTC)
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run News Aggregator Script and Store in Supabase
        env: # Pass all necessary API keys and Supabase credentials
          NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }} # New
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }} # New (service_role key)
        run: |
          python app.py # The script now handles storage directly

      # The "Upload Briefing Output (Optional)" step is removed as output goes to Supabase
